---

- hosts: localhost
  connection: local
  tasks:
    - shell: apt-get install -y python-apt
      become: True
    - shell: apt-get install -y {{ item }}
      become: True
      with_items:
        - git
        - gettext
        - libncurses5-dev
        - libacl1-dev
        - libgpm-dev
        - libperl-dev
        - python-dev
        - python3-dev
        - ruby-dev
        - lua5.2
        - liblua5.2-dev
        - luajit
        - libluajit-5.1-dev
        - autoconf
        - automake
        - cproto
    - shell: git clone https://github.com/vim/vim.git /tmp/vim creates=/tmp/vim
      become: True
    - shell: chmod 777 -R /tmp/vim
      become: True
    - shell: git checkout v8.0.0045 chdir=/tmp/vim
    - shell: CONFIGURE_OPTS="--enable-shared" pyenv install 2.7.6
    - shell: CONFIGURE_OPTS="--enable-shared" pyenv install 3.4.0
    - shell: pyenv versions
    - shell: make distclean chdir=/tmp/vim/src
    - shell: pyenv global 2.7.6 3.4.0 && LDFLAGS="-Wl,-rpath=${HOME}/.pyenv/versions/2.7.6/lib:${HOME}/.pyenv/versions/3.4.0/lib" ./configure --with-features=huge --enable-perlinterp --enable-pythoninterp --enable-python3interp --enable-rubyinterp --enable-luainterp --with-luajit --enable-fail-if-missing chdir=/tmp/vim/src
    - shell: make chdir=/tmp/vim/src
    - shell: make install chdir=/tmp/vim/src
      become: True
