---

- hosts: localhost
  become: True
  connection: local
  tasks:
    - shell: apt-get install -y python-apt
    - apt: name={{ item }}
      with_items:
        - git
        - gettext
        - libncurses5-dev
        - libacl1-dev
        - libgpm-dev
        - libperl-dev
        - python-dev
        - python3-dev
        - ruby-dev
        - lua5.2
        - liblua5.2-dev
        - luajit
        - libluajit-5.1-dev
        - autoconf
        - automake
        - cproto
    - shell: git clone https://github.com/vim/vim.git /tmp/vim creates=/tmp/vim
    - shell: git checkout v8.0.0045 chdir=/tmp/vim
    - shell: ./configure --with-features=huge --enable-perlinterp --enable-pythoninterp --enable-python3interp --enable-rubyinterp --enable-luainterp --with-luajit --enable-fail-if-missing chdir=/tmp/vim/src
    - shell: make chdir=/tmp/vim/src
    - shell: make install chdir=/tmp/vim/src
